// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSRz9x8LG_Bw_iFmRGjCdTh6St6XbW40',
    appId: '1:924159946644:android:3003238c418827b2726981',
    messagingSenderId: '924159946644',
    projectId: 'todoapp-1243c',
    databaseURL: 'https://todoapp-1243c-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-1243c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFIQz3fzz_GAyfQtaSThSNI95d5j05Xak',
    appId: '1:924159946644:ios:c1208de2251829e7726981',
    messagingSenderId: '924159946644',
    projectId: 'todoapp-1243c',
    databaseURL: 'https://todoapp-1243c-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-1243c.firebasestorage.app',
    iosClientId: '924159946644-tjchv3ag5kg1ae0pru88rmd8rp0p2ipl.apps.googleusercontent.com',
    iosBundleId: 'com.todo.app.myTodo',
  );
}
